config/routes.rb
Rails.application.routes.draw do

  resources :carts

  get "/purchases", to: "purchases#index", as: "purchases"
  get "/purchases/:id", to: "purchases#show", as: "purchase"
  delete "/purchases", to: "purchases#destroy"

  resources :purchases
  resources :reviews
  resources :items
  resources :customers

  get "/login", to: "customers#login", as: "login"
  post "/handle_login", to: "customers#handle_login"
  post "/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"
  delete "/logout", to: "customers#logout", as: "logout"
  


  # post "/purchases", to: "purchases#add_to_cart"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer

  has_many :purchases 
  has_many :items, through: :purchases
  

  
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_secure_password

    has_many :reviews 
    has_many :items, through: :reviews 

    has_many :carts 
    has_many :purchases, through: :carts


end

app/models/item.rb
class Item < ApplicationRecord
    has_many :reviews 
    has_many :customers, through: :reviews 

    has_many :purchases 
    has_many :carts, through: :purchases
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_customer, :is_logged_in?

    def current_customer
        Customer.find_by(id: session[:customer_id])
    end

    def is_logged_in?
        !!current_customer
    end
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def create
    end

    def show
    end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def new
        @customer = Customer.new()
    end

    def create
        @customer = Customer.create(customer_params)
        @customer.carts.destroy_all
        Cart.create(customer_id: @customer.id)
        redirect_to items_path
    end

    def login
    end

    def handle_login
        @customer = Customer.find_by(username: params[:username])
        if @customer && @customer.authenticate(params[:password])
            session[:customer_id] = @customer.id
            @cart = Cart.find_by(customer_id: @customer.id)
            redirect_to items_path
        else
            flash[:errors] = ["Incorrect Username or Password"]
            redirect_to login_path
        end
    end

    def logout
        session[:customer_id] = nil
        redirect_to items_path
    end
    private

    def customer_params
        params.require(:customer).permit(:username, :password)
    end



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index 
        if params[:name]
            @items = Item.where('name LIKE ?', "%" + params[:name] + "%")
        else
            @items = Item.all 
        end 
    end 

    def show 
        @item = Item.find(params[:id])
        @purchase = Purchase.new
        @review = Review.new
        @items = Item.all
    end

    def add_to_cart 
    end 

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

    def index 
        @purchases = Purchase.all 
    end 

    def show
        @purchase = Purchase.find(params[:id])
    end

    def create
        @cart = current_customer.carts.find_by(customer_id: current_customer.id)
        if @cart 
            @purchase = @cart.purchases.new(purchase_params)
            @purchase.save
            @purchase.item.update(stock: @purchase.item.stock - 1)
            redirect_to purchases_path
        else  
            @cart = current_customer.carts.create(customer_id: current_customer.id)
            @purchase = @cart.purchases.new(purchase_params)
            @purchase.save
            @purchase.item.update(stock: @purchase.item.stock - 1)
            redirect_to purchases_path
        end 
    end

    def add_to_cart
    end 

    def destroy
        @purchase = Purchase.find(params[:id])
        @purchase.destroy
        @purchase.item.update(stock: @purchase.item.stock + 1)
        redirect_to purchases_path
    end


    private
    
    def purchase_params
        params.require(:purchase).permit(:cart_id, :item_id)
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    def new
        @review = Review.new()
    end

    def create
        @review = Review.create(review_params)
        redirect_to item_path(@review.item)
    end

    private

    def review_params  
        params.require(:review).permit(:customer_id, :item_id, :rating, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/carts/show.html.erb
<h1> Your Cart </h1>
<ul>
<% current_customer.purchases.each do |purchase| %>
    <li>
    <%= purchase.item.name %>
    </li>
<% end %>
</ul>

<p> Total: <%= current_customer.carts.last.items.sum {|item| item.price } %>

app/views/customers/login.html.erb
<div id="login">
    <% if flash[:errors] %>
        <% flash[:errors].each do |error|%>
            <%= error %>
        <% end %>
    <% end %>
<h1> Log In </h1>

<%= form_tag "handle_login" do %>
    <%= label_tag "Enter Username" %>
    <%= text_field_tag :username %><br>
    <%= label_tag "Enter Password" %>
    <%= password_field_tag :password %><br><br>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= submit_tag "Log In" %>
<% end %>
</div>

app/views/customers/new.html.erb
<h1> Sign Up Today! </h1>
<div id="login">
<%= form_for @customer do |f| %>
    <%= f.label "Enter Username" %>
    <%= f.text_field :username %><br>
    <%= f.label "Enter Password" %>
    <%= f.password_field :password %><br><br>
    <%= f.submit "Create account" %>
<% end %>
</div>

app/views/items/index.html.erb
<% if params[:name] && @items.count == 0 %>
    <h1>Sorry, no results found.</h1>
<% end %>
<div class="recommended"> 
  <% @items.sample(4).each do |item| %>
    <%= link_to item_path(item) do %>
        <%= image_tag("#{item.image}.jpg", size: "250x180", :style => "margin: 12px") %>
    <p><%= item.name %></p>
    <p>$<%= item.price %></p>
    <% end %>
  <% end %>
</div>
<div class="recommended">
  <% @items.sample(4).each do |item| %>
    <%= link_to item_path(item) do %>
        <%= image_tag("#{item.image}.jpg", size: "250x180", :style => "margin: 12px") %>
        <p><%= item.name %></p>
        <p>$<%= item.price %></p>
    <% end %>
  <% end %>
</div>

app/views/items/show.html.erb
<section> 
 <div id="image"> <%= image_tag "#{@item.image}.jpg", size: "570x325" %> </div>
 <div id="showcase">
    <h1><%= @item.name %></h1>

    <%= @item.description %>

    <p> Price: <%= "$ #{@item.price}" %><br></p>

    <p> Stock: <% if @item.stock == 0 %> No Longer in stock
               <% else%>
                  <%= @item.stock %><br></p>
                <% end %>
    <% if is_logged_in? && @item.stock > 0 %>
        <%= form_for @purchase do |f| %>
            <%= f.hidden_field :item_id, :value => @item.id %>  
            <%= f.hidden_field :cart_id, :value => current_customer.carts.find_by(customer_id: current_customer.id) %>  
            <%= f.submit "Add to cart" %>
        <% end %>
    <% elsif is_logged_in? %><br>
        Cannot order
    <% else %>
    <p>Sign up or log in above to add item to cart</p>
<% end %>
 </div>
</section>

<%= render "/reviews/show.html.erb" %>
<%= render "/reviews/new.html.erb" %>

<h4>People Who Bought This Also Purchased</h4>
<% @items.sample(5).each do |item| %>
    <%= link_to item_path(item) do %>
        <%= image_tag("#{item.image}.jpg", size: "250x170", :style => "margin: 12px") %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phase2Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div id="logo">
        <%= link_to items_path do %>
          <%= image_tag "logo.jpg", size: "130x80" %>
        <% end %>
      </div>

     <div id="search_bar">
        <%= form_tag(items_path, method: :get) do %>
          <%= text_field_tag(:name)%>
          <%= submit_tag("Search")%>
        <% end %>
    </div>

    <div id="user">
      <% if is_logged_in? %>
        Logged in as: <%= current_customer.username %>
        <%= button_to "Log out", logout_path, method: "delete" %>
      <% else %>
        <%= link_to "Sign up", new_customer_path %>
        <%= link_to "Log In", "/login" %>
      <% end %>
    </div>

    <div id="cart">
      <%= link_to purchases_path do %>
        <%= image_tag "shopping_cart.png", size: "60x50" %>
      <% end %>
    </div>

    </header>

    <%= yield %>
  </body>
</html>

app/views/purchases/index.html.erb
<% unless is_logged_in? %>
    <div class="error"> Please log in or sign up to view your cart. </div>
<% else %>
    <% if current_customer.purchases.count == 0 %>
    <div class="error"> Your cart is empty. </div>

    <% else %>
        <h1> Your Cart </h1>
        <% total = 0 %>
        <% current_customer.purchases.each do |purchase| %>
            <div id="item">
            <span><%= purchase.item.name %><br>
                  $<%= purchase.item.price %><br></span>
            <span><%= button_to "remove from cart", {:controller => :purchases, :action => 'destroy', :id => purchase.id }, method: "delete" %></span>
            </div>
            <% total += purchase.item.price %>
        <% end %>
        <div id="checkout">
        <p> Cart Item Total: <%= current_customer.purchases.count %> </p>
        <p> Subtotal: $<%= total %> </p>
        <%= button_to "Checkout", "https://www.paypal.com/", method: "get" %>
        </div>
    <% end %>
<% end %>

app/views/reviews/_new.html.erb
<% if is_logged_in? %>
<h4> Write A Review </h4>
<%= form_for @review do |f| %>
    <%= f.hidden_field :customer_id, :value => current_customer.id %>
    <%= f.hidden_field :item_id, :value => @item.id %>
    <%= f.collection_select :rating, (1..5).to_a, :itself, :itself %>
    <%= f.text_field :body %>
    <%= f.submit %>
<% end %>

<% end %>

app/views/reviews/_show.html.erb
    <ul>
        <% @item.reviews.each do |review| %>
        <li>
            <%= review.customer.username %><br>
            <% review.rating.times do  %>
               🌟
            <% end %><br>
        <%= review.body %>
        </li>
        <% end %>
    </ul>